import { Area, Sensor, Alert, Action, Wall, User } from '../types/sensor';

export const MOCK_AREAS: Area[] = [
    {
        id: 1,
        name: 'Main Building',
        area_type: 'building',
        sensor_count: 5,
        subareas: [2, 3],
        parent_id: null,
        description: 'Primary facility building',
        status: 'Normal',
        createdAt: new Date().toISOString(),
    },
    {
        id: 2,
        name: 'Ground Floor',
        area_type: 'floor',
        sensor_count: 3,
        subareas: [4],
        parent_id: 1,
        description: 'Main lobby and reception',
        status: 'Normal',
        createdAt: new Date().toISOString(),
        area_plan: '/assets/test_plans/floor2.jpg',
        offset_z: 0,
        floor_level: 0,
    },
    {
        id: 3,
        name: 'Server Room',
        area_type: 'room',
        sensor_count: 2,
        subareas: [],
        parent_id: 1,
        description: 'Secure data center area',
        status: 'Warning',
        createdAt: new Date().toISOString(),
        area_plan: '/assets/test_plans/floor3.png',
        offset_z: 4,
        floor_level: 1,
    },
    {
        id: 4,
        name: 'Lobby East',
        area_type: 'room',
        sensor_count: 2,
        subareas: [],
        parent_id: 2,
        description: 'East wing entrance lobby',
        status: 'Normal',
        createdAt: new Date().toISOString(),
        area_plan: '/assets/test_plans/floor4.png',
        offset_z: 0,
        floor_level: 0,
    }
];

export const MOCK_SENSORS: Sensor[] = [
    {
        id: '1',
        name: 'Lobby Temp 01',
        sensor_type: 'HALO_3C',
        mac_address: '00:11:22:33:44:55',
        ip_address: '192.168.1.101',
        status: 'active',
        is_active: true,
        is_online: true,
        area: 4,
        x_val: 0.2,
        y_val: 0.3,
        z_val: 0.9,
        last_heartbeat: new Date().toISOString(),
        walls: [
            {
                id: 10,
                r_x1: 0.1,
                r_y1: 0.2,
                r_x2: 0.3,
                r_y2: 0.2,
                r_height: 2,
                color: '#34d399',
                opacity: 0.8,
            }
        ]
    },
    {
        id: '2',
        name: 'Server Room Smoke',
        sensor_type: 'HALO_SMART',
        mac_address: 'AA:BB:CC:DD:EE:FF',
        ip_address: '192.168.1.102',
        status: 'warning',
        is_active: true,
        is_online: true,
        area: 3,
        x_val: 0.5,
        y_val: 0.5,
        z_val: 0.9,
        last_heartbeat: new Date().toISOString(),
        walls: [
            {
                id: 11,
                r_x1: 0.4,
                r_y1: 0.4,
                r_x2: 0.6,
                r_y2: 0.4,
                r_height: 2.5,
                color: '#fbbf24',
                opacity: 0.8,
            },
            {
                id: 12,
                r_x1: 0.6,
                r_y1: 0.4,
                r_x2: 0.6,
                r_y2: 0.6,
                r_height: 2.5,
                color: '#fbbf24',
                opacity: 0.8,
            }
        ]
    },
    {
        id: '3',
        name: 'Lobby Humidity',
        sensor_type: 'HALO_3C',
        mac_address: '11:22:33:44:55:66',
        ip_address: '192.168.1.103',
        status: 'active',
        is_active: true,
        is_online: true,
        area: 4,
        x_val: 0.7,
        y_val: 0.8,
        z_val: 0.9,
    },
    {
        id: '4',
        name: 'Unassigned Temp 01',
        sensor_type: 'HALO_SMART',
        mac_address: '22:33:44:55:66:77',
        ip_address: '192.168.1.104',
        status: 'active',
        is_active: true,
        is_online: true,
        x_val: 0.1,
        y_val: 0.1,
        z_val: 0.9,
    },
    {
        id: '5',
        name: 'Unassigned Smoke 01',
        sensor_type: 'HALO_3C',
        mac_address: '33:44:55:66:77:88',
        ip_address: '192.168.1.105',
        status: 'active',
        is_active: false,
        is_online: false,
        x_val: 0.2,
        y_val: 0.2,
        z_val: 0.9,
    }
];

export const MOCK_USERS: User[] = [
    {
        id: 1,
        username: 'admin',
        email: 'admin@example.com',
        first_name: 'System',
        last_name: 'Administrator',
        role: 'Admin',
        is_active: true,
        created_at: new Date().toISOString(),
        assigned_area_ids: [1, 2, 3, 4],
    },
    {
        id: 2,
        username: 'security_officer',
        email: 'security@example.com',
        first_name: 'Security',
        last_name: 'Officer',
        role: 'Viewer',
        is_active: true,
        created_at: new Date().toISOString(),
        assigned_area_ids: [2, 4],
    }
];


export const MOCK_ALERTS: Alert[] = [
    {
        id: 101,
        type: 'high_temperature',
        source: 'Internal',
        status: 'active',
        description: 'High temperature detected in Server Room',
        sensor: 2,
        sensor_name: 'Server Room Smoke',
        area: 3,
        area_name: 'Server Room',
        alert_actions: [],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 102,
        type: 'motion_alert',
        source: 'Internal',
        status: 'resolved',
        description: 'Unauthorized motion in Lobby East',
        sensor: 1,
        sensor_name: 'Lobby Temp 01',
        area: 4,
        area_name: 'Lobby East',
        alert_actions: [],
        created_at: new Date(Date.now() - 3600000).toISOString(),
        updated_at: new Date().toISOString(),
    }
];

export const MOCK_ACTIONS: Action[] = [
    {
        id: 1,
        name: 'Email Admin',
        type: 'email',
        recipients: [1],
        message_template: 'Alert: {description} triggered on {sensor_name}',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 2,
        name: 'Push to Security',
        type: 'push_notification',
        recipients: [2],
        message_template: 'Security Alert: {description}',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }
];

export const MOCK_WALLS: Wall[] = [
    {
        id: 1,
        r_x1: 0,
        r_y1: 0,
        r_x2: 1,
        r_y2: 0,
        r_height: 2.4,
        color: '#FF0000',
        opacity: 0.5,
        area_ids: [4],
    },
    {
        id: 2,
        r_x1: 1,
        r_y1: 0,
        r_x2: 1,
        r_y2: 1,
        r_height: 2.4,
        color: '#00FF00',
        opacity: 0.5,
        area_ids: [4],
    },
    {
        id: 3,
        r_x1: 0,
        r_y1: 0,
        r_x2: 0,
        r_y2: 5,
        r_height: 3,
        color: '#3498db',
        opacity: 0.6,
        area_ids: [2],
    },
    {
        id: 4,
        r_x1: 0,
        r_y1: 5,
        r_x2: 8,
        r_y2: 5,
        r_height: 3,
        color: '#3498db',
        opacity: 0.6,
        area_ids: [2],
    },
    {
        id: 5,
        r_x1: 0,
        r_y1: 0,
        r_x2: 4,
        r_y2: 0,
        r_height: 2.4,
        color: '#e67e22',
        opacity: 0.5,
        area_ids: [3],
    },
    {
        id: 6,
        r_x1: 4,
        r_y1: 0,
        r_x2: 4,
        r_y2: 4,
        r_height: 2.4,
        color: '#e67e22',
        opacity: 0.5,
        area_ids: [3],
    }
];

export const MOCK_AGGREGATED_DATA = {
    aggregated_data: {
        temperature_min: 22.5,
        temperature_max: 28.3,
        temperature_min_sensor: 1,
        temperature_max_sensor: 2,

        humidity_min: 45.0,
        humidity_max: 67.0,
        humidity_min_sensor: 3,
        humidity_max_sensor: 1,

        co2_min: 400,
        co2_max: 850,
        co2_min_sensor: 2,
        co2_max_sensor: 3,

        tvoc_min: 50,
        tvoc_max: 220,
        tvoc_min_sensor: 1,
        tvoc_max_sensor: 2,

        pm25_min: 5,
        pm25_max: 35,
        pm25_min_sensor: 2,
        pm25_max_sensor: 3,

        pm10_min: 10,
        pm10_max: 55,
        pm10_min_sensor: 1,
        pm10_max_sensor: 2,

        pm1_min: 3,
        pm1_max: 20,
        pm1_min_sensor: 3,
        pm1_max_sensor: 1,

        noise_min: 35,
        noise_max: 72,
        noise_min_sensor: 2,
        noise_max_sensor: 3,

        co_min: 0.5,
        co_max: 4.2,
        co_min_sensor: 1,
        co_max_sensor: 2,

        pressure_min: 1008,
        pressure_max: 1013,
        pressure_min_sensor: 3,
        pressure_max_sensor: 1,

        aqi_min: 30,
        aqi_max: 85,
        aqi_min_sensor: 2,
        aqi_max_sensor: 3,

        light_min: 300,
        light_max: 550,
        light_min_sensor: 1,
        light_max_sensor: 2,

        sound_min: 42,
        sound_max: 68,
        sound_min_sensor: 2,
        sound_max_sensor: 3,

        movement_min: 0,
        movement_max: 12,
        movement_min_sensor: 1,
        movement_max_sensor: 3,

        health_min: 88,
        health_max: 98,
        health_min_sensor: 2,
        health_max_sensor: 1,
    }
};

