import { Area, Sensor, Alert, Action, Wall, User, AlertFilter, AlertFilterGroup } from '../types/sensor';

export const MOCK_AREAS: Area[] = [
    {
        id: 1,
        name: 'Main Building',
        area_type: 'building',
        sensor_count: 5,
        subareas: [2, 3],
        parent_id: null,
        description: 'Primary facility building',
        status: 'Normal',
        createdAt: new Date().toISOString(),
    },
    {
        id: 2,
        name: 'Ground Floor',
        area_type: 'floor',
        sensor_count: 3,
        subareas: [4],
        parent_id: 1,
        description: 'Main lobby and reception',
        status: 'Normal',
        createdAt: new Date().toISOString(),
        area_plan: '/assets/test_plans/floor2.jpg',
        offset_z: 0,
        floor_level: 0,
    },
    {
        id: 3,
        name: 'Server Room',
        area_type: 'room',
        sensor_count: 2,
        subareas: [],
        parent_id: 1,
        description: 'Secure data center area',
        status: 'Warning',
        createdAt: new Date().toISOString(),
        area_plan: '/assets/test_plans/floor3.png',
        offset_z: 4,
        floor_level: 1,
    },
    {
        id: 4,
        name: 'Lobby East',
        area_type: 'room',
        sensor_count: 2,
        subareas: [],
        parent_id: 2,
        description: 'East wing entrance lobby',
        status: 'Normal',
        createdAt: new Date().toISOString(),
        area_plan: '/assets/test_plans/floor4.png',
        offset_z: 0,
        floor_level: 0,
    }
];

export const MOCK_SENSORS: Sensor[] = [
    {
        id: '1',
        name: 'Lobby Temp 01',
        sensor_type: 'HALO_3C',
        mac_address: '00:11:22:33:44:55',
        ip_address: '192.168.1.101',
        status: 'active',
        is_active: true,
        is_online: true,
        area: 4,
        x_val: 0.2,
        y_val: 0.3,
        z_val: 0.9,
        last_heartbeat: new Date().toISOString(),
        walls: [
            {
                id: 10,
                r_x1: 0.1,
                r_y1: 0.2,
                r_x2: 0.3,
                r_y2: 0.2,
                r_height: 2,
                color: '#34d399',
                opacity: 0.8,
            }
        ]
    },
    {
        id: '2',
        name: 'Server Room Smoke',
        sensor_type: 'HALO_SMART',
        mac_address: 'AA:BB:CC:DD:EE:FF',
        ip_address: '192.168.1.102',
        status: 'warning',
        is_active: true,
        is_online: true,
        area: 3,
        x_val: 0.5,
        y_val: 0.5,
        z_val: 0.9,
        last_heartbeat: new Date().toISOString(),
        walls: [
            {
                id: 11,
                r_x1: 0.4,
                r_y1: 0.4,
                r_x2: 0.6,
                r_y2: 0.4,
                r_height: 2.5,
                color: '#fbbf24',
                opacity: 0.8,
            },
            {
                id: 12,
                r_x1: 0.6,
                r_y1: 0.4,
                r_x2: 0.6,
                r_y2: 0.6,
                r_height: 2.5,
                color: '#fbbf24',
                opacity: 0.8,
            }
        ]
    },
    {
        id: '3',
        name: 'Lobby Humidity',
        sensor_type: 'HALO_3C',
        mac_address: '11:22:33:44:55:66',
        ip_address: '192.168.1.103',
        status: 'active',
        is_active: true,
        is_online: true,
        area: 4,
        x_val: 0.7,
        y_val: 0.8,
        z_val: 0.9,
    },
    {
        id: '4',
        name: 'Unassigned Temp 01',
        sensor_type: 'HALO_SMART',
        mac_address: '22:33:44:55:66:77',
        ip_address: '192.168.1.104',
        status: 'active',
        is_active: true,
        is_online: true,
        x_val: 0.1,
        y_val: 0.1,
        z_val: 0.9,
    },
    {
        id: '5',
        name: 'Unassigned Smoke 01',
        sensor_type: 'HALO_3C',
        mac_address: '33:44:55:66:77:88',
        ip_address: '192.168.1.105',
        status: 'active',
        is_active: false,
        is_online: false,
        x_val: 0.2,
        y_val: 0.2,
        z_val: 0.9,
    }
];

export const MOCK_USERS: User[] = [
    {
        id: 1,
        username: 'admin',
        email: 'admin@example.com',
        first_name: 'System',
        last_name: 'Administrator',
        role: 'Admin',
        is_active: true,
        created_at: new Date().toISOString(),
        assigned_area_ids: [1, 2, 3, 4],
    },
    {
        id: 2,
        username: 'security_officer',
        email: 'security@example.com',
        first_name: 'Security',
        last_name: 'Officer',
        role: 'Viewer',
        is_active: true,
        created_at: new Date().toISOString(),
        assigned_area_ids: [2, 4],
    }
];


export const MOCK_ALERTS: Alert[] = [
    {
        id: 101,
        type: 'high_temperature',
        source: 'Internal',
        status: 'active',
        description: 'High temperature detected in Server Room',
        sensor: 2,
        sensor_name: 'Server Room Smoke',
        area: 3,
        area_name: 'Server Room',
        alert_actions: [],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 102,
        type: 'motion_alert',
        source: 'Internal',
        status: 'resolved',
        description: 'Unauthorized motion in Lobby East',
        sensor: 1,
        sensor_name: 'Lobby Temp 01',
        area: 4,
        area_name: 'Lobby East',
        alert_actions: [],
        created_at: new Date(Date.now() - 3600000).toISOString(),
        updated_at: new Date().toISOString(),
    }
];

export const MOCK_ACTIONS: Action[] = [
    {
        id: 1,
        name: 'Infrastructure Support Group (Email)',
        type: 'email',
        recipients: [
            { id: 101, username: 'infra_mgr', email: 'infra.manager@abaci.com', first_name: 'David', last_name: 'Chen' }
        ],
        message_template: 'CRITICAL: {description} detected in {area_name}. Sensor: {sensor_name}',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 2,
        name: 'Security Desk Priority 1 (Push)',
        type: 'push_notification',
        recipients: [
            { id: 201, username: 'sec_desk_01', email: 'security.desk@abaci.com', first_name: 'John', last_name: 'Smith' },
            { id: 202, username: 'sec_supervisor', email: 'sec.sup@abaci.com', first_name: 'Sarah', last_name: 'Vance' }
        ],
        message_template: 'SECURITY ALERT: [ {type} ] at {area_name}. Immediate response requested.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 3,
        name: 'Thermal API Integration (Webhook)',
        type: 'webhook',
        recipients: [],
        message_template: '{"event": "{type}", "area": "{area_name}", "timestamp": "{created_at}"}',
        is_active: true,
        webhook_url: 'https://hooks.abaci-internal.com/alerts/thermal',
        http_method: 'POST',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 4,
        name: 'Emergency SMS Alert (Security)',
        type: 'sms',
        recipients: [
            { id: 201, username: 'sec_desk_01', email: 'security.desk@abaci.com', first_name: 'John', last_name: 'Smith' }
        ],
        message_template: 'HALO ALERT: {type} in {area_name}. CHECK DASHBOARD.',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 5,
        name: 'Internal Dev Portal (alerts-main)',
        type: 'slack',
        recipients: [],
        message_template: '*Alert Triggered:* {description}\n*Location:* {area_name}',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 6,
        name: 'IT Ops Center (MS Teams)',
        type: 'teams',
        recipients: [],
        message_template: 'System Alert: {type} detected at {sensor_name}',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 7,
        name: 'Flash Visual Warning (Device LED)',
        type: 'device_notification',
        recipients: [],
        device_type: 'HALO_3C',
        device_list: ['Lobby Temp 01', 'Server Room Smoke'],
        device_led_color: 16711680, // Red
        device_led_pattern: 200004, // Fast Flash
        device_led_priority: 8,
        is_active: true,
        message_template: 'LED Command Sent',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }
];

export const MOCK_ALERT_FILTERS: AlertFilter[] = [
    {
        id: 1,
        name: 'Data Center A - Thermal Threshold',
        description: 'Triggers when Server Room A exceeds safe operating temperature (35°C)',
        area_ids: [3],
        area_list: [MOCK_AREAS[2]], // Server Room
        alert_types: ['high_temperature', 'temp_c'],
        source_types: ['Internal'],
        action_for_max: true,
        action_for_min: false,
        action_for_threshold: true,
        weekdays: [0, 1, 2, 3, 4, 5, 6],
        is_active: true,
        action_ids: [1, 3, 5],
        actions: [MOCK_ACTIONS[0], MOCK_ACTIONS[2], MOCK_ACTIONS[4]], // Email, Webhook, Slack
        sensor_config_ids: [1],
        sensor_group_ids: [10],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 2,
        name: 'After-Hours Motion Detection (East Lobby)',
        description: 'Security loop for unauthorized motion in lobby zones between 10 PM and 6 AM',
        area_ids: [4],
        area_list: [MOCK_AREAS[3]], // Lobby East
        alert_types: ['motion_alert', 'motion'],
        source_types: ['Internal'],
        action_for_threshold: true,
        action_for_min: false,
        action_for_max: false,
        start_time: '22:00',
        end_time: '06:00',
        weekdays: [0, 1, 2, 3, 4, 5, 6],
        is_active: true,
        action_ids: [2, 4, 7],
        actions: [MOCK_ACTIONS[1], MOCK_ACTIONS[3], MOCK_ACTIONS[6]], // Push, SMS, Device
        sensor_config_ids: [2],
        sensor_group_ids: [11],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 3,
        name: 'Data Center A - Redundant Environmental Check',
        description: 'CONFLICT CASE: Overlaps with Thermal Threshold (ID 1) in same room/type.',
        area_ids: [3],
        area_list: [MOCK_AREAS[2]], // Server Room
        alert_types: ['high_temperature'],
        source_types: ['Internal'],
        action_for_max: true,
        action_for_min: false,
        action_for_threshold: false,
        weekdays: [0, 1, 2, 3, 4, 5, 6],
        is_active: true,
        action_ids: [6],
        actions: [MOCK_ACTIONS[5]], // Teams
        sensor_config_ids: [3],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 4,
        name: 'Warehouse B - Off-Hours Smoke Sensor (Draft)',
        description: 'DEAD CASE: No actions linked. Safety monitoring for Building 1 / Basement.',
        area_ids: [1, 2],
        area_list: [MOCK_AREAS[0], MOCK_AREAS[1]], // Main Building, Ground Floor
        alert_types: ['smoke_detected'],
        source_types: ['Internal'],
        action_for_threshold: true,
        action_for_min: false,
        action_for_max: false,
        weekdays: [0, 1, 2, 3, 4, 5, 6],
        is_active: true,
        action_ids: [],
        actions: [],
        sensor_config_ids: [4],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 5,
        name: 'Weekend Perimeter Security Loop',
        description: 'SILENT CASE: Triggers only on Saturdays and Sundays - silent during weekdays.',
        area_ids: [1],
        area_list: [MOCK_AREAS[0]], // Main Building
        alert_types: ['smoke_detected', 'pm25'],
        source_types: ['Internal'],
        action_for_threshold: true,
        action_for_min: false,
        action_for_max: false,
        weekdays: [5, 6], // Saturday, Sunday
        is_active: true,
        action_ids: [1],
        actions: [MOCK_ACTIONS[0]],
        sensor_config_ids: [5],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }
];

export const MOCK_ALERT_FILTER_GROUPS: AlertFilterGroup[] = [
    {
        id: 1,
        name: 'Critical Infrastructure safety',
        description: 'High-priority monitoring for Server Rooms and Executive Areas',
        alert_filters: [MOCK_ALERT_FILTERS[0], MOCK_ALERT_FILTERS[1], MOCK_ALERT_FILTERS[3], MOCK_ALERT_FILTERS[4]],
        alert_filter_ids: [1, 2, 4, 5],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 2,
        name: 'Diagnostic & Conflict Tests',
        description: 'System-generated group for edge case validation (Overlaps)',
        alert_filters: [MOCK_ALERT_FILTERS[0], MOCK_ALERT_FILTERS[2]],
        alert_filter_ids: [1, 3],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }
];

export const MOCK_WALLS: Wall[] = [
    {
        id: 1,
        r_x1: 0,
        r_y1: 0,
        r_x2: 1,
        r_y2: 0,
        r_height: 2.4,
        color: '#FF0000',
        opacity: 0.5,
        area_ids: [4],
    },
    {
        id: 2,
        r_x1: 1,
        r_y1: 0,
        r_x2: 1,
        r_y2: 1,
        r_height: 2.4,
        color: '#00FF00',
        opacity: 0.5,
        area_ids: [4],
    },
    {
        id: 3,
        r_x1: 0,
        r_y1: 0,
        r_x2: 0,
        r_y2: 5,
        r_height: 3,
        color: '#3498db',
        opacity: 0.6,
        area_ids: [2],
    },
    {
        id: 4,
        r_x1: 0,
        r_y1: 5,
        r_x2: 8,
        r_y2: 5,
        r_height: 3,
        color: '#3498db',
        opacity: 0.6,
        area_ids: [2],
    },
    {
        id: 5,
        r_x1: 0,
        r_y1: 0,
        r_x2: 4,
        r_y2: 0,
        r_height: 2.4,
        color: '#e67e22',
        opacity: 0.5,
        area_ids: [3],
    },
    {
        id: 6,
        r_x1: 4,
        r_y1: 0,
        r_x2: 4,
        r_y2: 4,
        r_height: 2.4,
        color: '#e67e22',
        opacity: 0.5,
        area_ids: [3],
    }
];

export const MOCK_AGGREGATED_DATA = {
    aggregated_data: {
        "temperature_min": 22.5,
        "temperature_max": 28.3,
        "temperature_min_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },
        "temperature_max_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },

        "humidity_min": 45.0,
        "humidity_max": 67.0,
        "humidity_min_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },
        "humidity_max_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },

        "co2_min": 400,
        "co2_max": 850,
        "co2_min_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },
        "co2_max_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },

        "tvoc_min": 50,
        "tvoc_max": 220,
        "tvoc_min_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },
        "tvoc_max_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },

        "pm25_min": 5,
        "pm25_max": 35,
        "pm25_min_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },
        "pm25_max_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },

        "pm10_min": 10,
        "pm10_max": 55,
        "pm10_min_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },
        "pm10_max_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },

        "pm1_min": 3,
        "pm1_max": 20,
        "pm1_min_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },
        "pm1_max_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },

        "noise_min": 35,
        "noise_max": 72,
        "noise_min_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },
        "noise_max_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },

        "co_min": 0.5,
        "co_max": 4.2,
        "co_min_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },
        "co_max_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },

        "pressure_min": 1008,
        "pressure_max": 1013,
        "pressure_min_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },
        "pressure_max_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },

        "aqi_min": 30,
        "aqi_max": 85,
        "aqi_min_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },
        "aqi_max_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },

        "light_min": 300,
        "light_max": 550,
        "light_min_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },
        "light_max_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },

        "sound_min": 42,
        "sound_max": 68,
        "sound_min_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },
        "sound_max_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },

        "movement_min": 0,
        "movement_max": 12,
        "movement_min_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" },
        "movement_max_sensor": { "sensor_id": 3, "sensor__name": "Lobby Humidity" },

        "health_min": 88,
        "health_max": 98,
        "health_min_sensor": { "sensor_id": 2, "sensor__name": "Server Room Smoke" },
        "health_max_sensor": { "sensor_id": 1, "sensor__name": "Lobby Temp 01" }
    }
};

export const MOCK_AGGREGATED_DATA_BY_FLOOR: Record<number, any> = {
    // ── HQ Campus (id: 1) ─────────────────────────────────────────────────────
    1: {
        temperature_min: 19.6, temperature_max: 38.2,
        humidity_min: 28.4, humidity_max: 62.5,
        light_min: 80, light_max: 640,
        pressure_min: 1000.0, pressure_max: 1014.0,
        sound_min: 28, sound_max: 110,
        co2_min: 428, co2_max: 1298,
        tvoc_min: 45, tvoc_max: 342,
        pm1_min: 2, pm1_max: 18,
        pm25_min: 3, pm25_max: 28,
        pm10_min: 5, pm10_max: 45,
        aqi_min: 16, aqi_max: 118,
        health_min: 2.2, health_max: 4.7,
        noise_min: 28, noise_max: 110,
        motion_min: 2, motion_max: 95,
        movement_min: 1, movement_max: 90,
        co_min: 0.3, co_max: 2.1,
        no2_min: 8, no2_max: 32,
        nh3_min: 0.0, nh3_max: 0.8,
    },

    // ── North Block (id: 2) ───────────────────────────────────────────────────
    2: {
        temperature_min: 22.4, temperature_max: 38.2,
        humidity_min: 28.4, humidity_max: 62.5,
        light_min: 120, light_max: 640,
        pressure_min: 1012.8, pressure_max: 1014.0,
        sound_min: 38, sound_max: 71,
        co2_min: 465, co2_max: 1298,
        tvoc_min: 55, tvoc_max: 342,
        pm1_min: 2, pm1_max: 18,
        pm25_min: 3, pm25_max: 28,
        pm10_min: 5, pm10_max: 45,
        aqi_min: 22, aqi_max: 118,
        health_min: 2.8, health_max: 4.2,
        noise_min: 38, noise_max: 71,
        motion_min: 5, motion_max: 88,
        movement_min: 2, movement_max: 72,
        co_min: 0.5, co_max: 2.1,
        no2_min: 8, no2_max: 32,
        nh3_min: 0.0, nh3_max: 0.8,
    },

    // ── South Block (id: 3) ───────────────────────────────────────────────────
    3: {
        temperature_min: 19.6, temperature_max: 19.6,
        humidity_min: 55.8, humidity_max: 55.8,
        light_min: 80, light_max: 80,
        pressure_min: 1013.8, pressure_max: 1013.8,
        sound_min: 28, sound_max: 28,
        co2_min: 428, co2_max: 428,
        tvoc_min: 45, tvoc_max: 45,
        pm1_min: 2, pm1_max: 2,
        pm25_min: 6, pm25_max: 6,
        pm10_min: 9, pm10_max: 9,
        aqi_min: 18, aqi_max: 18,
        health_min: 4.6, health_max: 4.6,
        noise_min: 28, noise_max: 28,
        motion_min: 2, motion_max: 2,
        movement_min: 1, movement_max: 1,
        co_min: 0.3, co_max: 0.3,
        no2_min: 9, no2_max: 9,
        nh3_min: 0.0, nh3_max: 0.0,
    },

    // ── Tower Block (id: 4) ───────────────────────────────────────────────────
    4: {
        temperature_min: 20.8, temperature_max: 25.0,
        humidity_min: 40.0, humidity_max: 52.0,
        light_min: 300, light_max: 580,
        pressure_min: 1000.0, pressure_max: 1013.0,
        sound_min: 28, sound_max: 110,
        co2_min: 465, co2_max: 705,
        tvoc_min: 55, tvoc_max: 110,
        pm1_min: 2, pm1_max: 6,
        pm25_min: 3, pm25_max: 10,
        pm10_min: 5, pm10_max: 16,
        aqi_min: 16, aqi_max: 55,
        health_min: 2.2, health_max: 4.7,
        noise_min: 28, noise_max: 110,
        motion_min: 8, motion_max: 95,
        movement_min: 4, movement_max: 90,
        co_min: 0.3, co_max: 0.9,
        no2_min: 8, no2_max: 20,
        nh3_min: 0.0, nh3_max: 0.2,
    },
};

