import React, { useContext, useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import PropTypes from 'prop-types';
import Modal, {
    ModalBody,
    ModalFooter,
    ModalHeader,
    ModalTitle,
} from '../../../components/bootstrap/Modal';
import Button from '../../../components/bootstrap/Button';
import { authAxios } from '../../../axiosInstance';
import AuthContext from '../../../contexts/authContext';
import SaveIconButton from '../../../components/CustomComponent/Buttons/SaveIconButton';
import FormGroup from '../../../components/bootstrap/forms/FormGroup';
import ProfilePicUploadWithState from '../../../components/CustomComponent/ProfilePicUploadWithState';
import Card, { CardBody, CardHeader } from '../../../components/bootstrap/Card';
import ReactSelectComponent from '../../../components/CustomComponent/Select/ReactSelectComponent';
import useToasterNotification from '../../../hooks/useToasterNotification';

const AddUser = ({ isOpen, setIsOpen, title, onSuccess }) => {
    const {
        register,
        handleSubmit,
        watch,
        control,
        getValues,
        setValue,
        formState: { errors },
    } = useForm({});

    const partyType = watch('party_type');
    const [waitingForAxios, setWaitingForAxios] = useState(false);
    const [image, setImage] = useState(null);
    const [passwordType, setPasswordType] = useState('custom'); // 'autogenerated' or 'custom'
    const [showPassword, setShowPassword] = useState(false);
    const [forcePasswordChange, setForcePasswordChange] = useState(false);
    const [options, setOptions] = useState([]);
    const { showErrorNotification } = useToasterNotification();
    const [optionsLoading, setOptionsLoading] = useState(false);
    const [designationOptions, setDesignationOptions] = useState([]);
    const [rolesOptions, setRolesOptions] = useState([]);

    useEffect(() => {
        const fetchDesignationOptions = async () => {
            const response = await authAxios.get('/users/designations/?pagination=false&minimal=true&status=Active');
            setDesignationOptions(response.data.map((data) => ({
                label: data.name,
                value: data.id,
            })));
        };
        fetchDesignationOptions();
    }, []);

    const fetchData = async (type: string) => {
        setValue('establishment_gtcc', null);
        setValue('role', null);
        setOptionsLoading(true);
        setOptions([]);
        let response;
        try {
            switch (type) {
                case 'Establishment':
                    response = await authAxios.get('/region/establishments/?pagination=false&minimal=true&status=Active');
                    setOptions(response.data.map((data) => ({
                        label: data.establishment_name,
                        value: data.id,
                    })));
                    break;
                case 'GTCC':
                    response = await authAxios.get('/region/gtccs/?pagination=false&minimal=true&status=Active');
                    setOptions(response.data.map((data) => ({
                        label: data.name,
                        value: data.id,
                    })));
                    break;
                case 'Authority':
                    response = await authAxios.get('/region/authorities/?pagination=false&minimal=true&status=Active');
                    setOptions(response.data.map((data) => ({
                        label: data.name,
                        value: data.id,
                    })));
                    break;
                default:
                    break;
            }
            const fetchRolesOptions = async () => {
                const response = await authAxios.get(`/users/roles/?pagination=false&minimal=true&status=Active&party_type=${type}`);
                setRolesOptions(response.data.map((data) => ({
                    label: data.name,
                    value: data.id,
                })));
            }
            fetchRolesOptions();
        } catch (error) {
            showErrorNotification(error);
        } finally {
            setOptionsLoading(false);
        }

    }

    const onSubmit = (data) => {
        setWaitingForAxios(true);
        // Prepare form data as needed for your API
        const formData: any = {
            first_name: data.first_name,
            last_name: data.last_name,
            email: data.email,
            party_type: data.party_type,
            personal_contact_number: data.personal_contact_number,
            office_contact_number: data.office_contact_number,
            alternate_email: data.alternate_email,
            role_id: data.role.value,
        };
        if (partyType === 'Establishment') {
            formData.establishment_id = data.establishment_gtcc.value;
        }
        if (partyType === 'GTCC') {
            formData.gtcc_id = data.establishment_gtcc.value;
        }
        if (partyType === 'Authority') {
            formData.authority_id = data.authority_id.value;
        }
        if (data.designation) {
            formData.designation_id = data.designation.value;
        }
        if (image) {
            formData.avatar = image;
        }

        // Add password configuration
        if (passwordType === 'custom' && data.console_password) {
            formData.password = data.console_password;
            formData.password_reset_required = forcePasswordChange;

        } else {
            formData.status = 'Pending';

        }
        // formData.password_type = passwordType;
        let url = `/users/user/`;
        authAxios
            .post(url, formData)
            .then((response) => {
                setWaitingForAxios(false);
                onSuccess(response.data);
                // tableRef.current.onQueryChange();
                setIsOpen(false);
            })
            .catch((error) => {
                setWaitingForAxios(false);
                showErrorNotification(error);
                // Handle error here
            });
    };

    const renderError = (fieldName) => {
        if (errors[fieldName]?.type === "required") {
            return <span className="field-required-class">*Required</span>;
        }
        if (errors[fieldName]?.type === "pattern") {
            // console.log(errors[fieldName]);
            return <span className="field-required-class">*{errors[fieldName]?.message.toString()}</span>;
        }
        return <></>;
    };

    return (
        <Modal isOpen={isOpen} setIsOpen={setIsOpen} size='lg' isCentered>
            <ModalHeader className='p-4' setIsOpen={setIsOpen}>
                <ModalTitle id='modaleditvehicle'>{title}</ModalTitle>
            </ModalHeader>
            <ModalBody className='d-flex flex-column gap-3 px-5 pb-5'>

                <div className='d-flex justify-content-center'>
                    <ProfilePicUploadWithState setImage={setImage} image={image} />
                </div>
                <FormGroup label="Party Type">
                    <select
                        className={errors?.party_type?.type === "required" ? 'form-control is-invalid' : 'form-control'}
                        {...register("party_type", {
                            required: true,
                            onChange: (e) => {
                                fetchData(e.target.value);
                            },
                        })}
                    >
                        {/* <option value="" disabled>Select Party Type</option> */}
                        <option value="">Select Party Type</option>
                        <option value="Region">Region</option>
                        <option value="GTCC">GTCC</option>
                        <option value="Establishment">Establishment</option>
                        <option value="Authority">Authority</option>
                        <option value="Organization">Organization</option>
                    </select>
                    {renderError('party_type')}
                </FormGroup>
                {['Establishment', 'GTCC', 'Authority', 'Vehicle'].includes(partyType) && (
                    <ReactSelectComponent
                        control={control}
                        name={partyType}
                        field_name="establishment_gtcc"
                        getValues={getValues}
                        errors={errors}
                        isLoading={optionsLoading}
                        options={options}
                        isRequired={true}
                        isClearable={true}
                    />)
                }

                <div style={{ marginBottom: '-10px' }}>
                    <ReactSelectComponent
                        control={control}
                        name='Role'
                        placeholder='Select Role'
                        field_name="role"
                        getValues={getValues}
                        errors={errors}
                        options={rolesOptions}
                        isClearable={true}
                        isRequired={true}
                    />
                </div>
                <FormGroup label="First Name">
                    <input
                        type="text"
                        className={errors?.first_name?.type === "required" ? 'form-control is-invalid' : 'form-control'}
                        placeholder="First Name"
                        {...register("first_name", {
                            required: true,
                        })}
                    />
                    {renderError('first_name')}
                </FormGroup>
                <FormGroup label="Last Name">
                    <input
                        type="text"
                        className={errors?.last_name?.type === "required" ? 'form-control is-invalid' : 'form-control'}
                        placeholder="Last Name"
                        {...register("last_name", {
                            required: true,
                        })}
                    />
                    {renderError('last_name')}
                </FormGroup>

                <div>
                    <ReactSelectComponent
                        control={control}
                        name='Designation'
                        placeholder='Select Designation'
                        field_name="designation"
                        getValues={getValues}
                        errors={errors}
                        options={designationOptions}
                        // isRequired={true}
                        isClearable={true}
                    />
                </div>



                <FormGroup label="Email">
                    <input
                        type="email"
                        className={errors?.email?.type === "required" || errors?.email?.type === "pattern" ? 'form-control is-invalid' : 'form-control'}
                        placeholder="Email"
                        {...register("email", {
                            required: true,
                            pattern: {
                                value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                                message: "Invalid email address",
                            },
                        })}
                    />
                    {renderError('email')}
                </FormGroup>


                <FormGroup label="Alternate Email">
                    <input
                        type="email"
                        className={errors?.alternate_email?.type === "required" || errors?.alternate_email?.type === "pattern" ? 'form-control is-invalid' : 'form-control'}
                        placeholder="Alternate Email"
                        {...register("alternate_email", {
                            // required: true,
                            pattern: {
                                value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                                message: "Invalid email address",
                            },
                        })}
                    />
                    {renderError('alternate_email')}
                </FormGroup>
                <FormGroup label="Contact Number">
                    <input
                        type="number"
                        onInput={(e: any) => e.target.value = e.target.value.slice(0, 10)}
                        // @ts-ignore
                        onWheel={(e: any) => e.target.blur()}
                        className={errors?.personal_contact_number?.type === "required" ? 'form-control is-invalid' : 'form-control'}
                        placeholder="Contact Number"
                        {...register("personal_contact_number", {
                            // required: true,
                            pattern: {
                                value: /^[0-9]+$/,
                                message: "Invalid contact number",
                            },
                        })}
                    />
                    {renderError('personal_contact_number')}
                </FormGroup>
                <FormGroup label="Office Contact Number">
                    <input
                        type="number"
                        onInput={(e: any) => e.target.value = e.target.value.slice(0, 10)}
                        // @ts-ignore
                        onWheel={(e: any) => e.target.blur()}
                        className={errors?.office_contact_number?.type === "required" ? 'form-control is-invalid' : 'form-control'}
                        placeholder="Office Contact Number"
                        {...register("office_contact_number", {
                            // required: true,
                        })}
                    />
                    {renderError('office_contact_number')}
                </FormGroup>



                {/* Console Password Section */}

                <Card>
                    <CardHeader>Password</CardHeader>
                    <CardBody>
                        <div>
                            <div className="mb-3">
                                <div className="form-check mb-2">
                                    <input
                                        className="form-check-input"
                                        type="radio"
                                        name="passwordType"
                                        id="autogenerated"
                                        value="autogenerated"
                                        checked={passwordType === 'autogenerated'}
                                        onChange={(e) => setPasswordType(e.target.value)}
                                    />
                                    <label className="form-check-label" htmlFor="autogenerated">
                                        <strong>Send invitation email</strong>
                                    </label>
                                    <div className="text-muted small">System will send an invitation email to the user, they can create a password.
                                    </div>
                                </div>

                                <div className="form-check">
                                    <input
                                        className="form-check-input"
                                        type="radio"
                                        name="passwordType"
                                        id="custom"
                                        value="custom"
                                        checked={passwordType === 'custom'}
                                        onChange={(e) => setPasswordType(e.target.value)}
                                    />
                                    <label className="form-check-label" htmlFor="custom">
                                        <strong>Custom password</strong>
                                    </label>
                                    <div className="text-muted small">
                                        Enter a custom password for the user.
                                    </div>
                                </div>
                            </div>

                            {/* Custom Password Input */}
                            {passwordType === 'custom' && (
                                <>
                                    <FormGroup label="Password">
                                        <div className="input-group">
                                            <input
                                                type={showPassword ? "text" : "password"}
                                                className={errors?.console_password?.type === "required" || errors?.console_password?.type === "pattern" ? 'form-control is-invalid' : 'form-control'}
                                                placeholder="Enter password"
                                                {...register("console_password", {
                                                    required: passwordType === 'custom',
                                                    pattern: {
                                                        value: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{}|`~]).{8,}$/,
                                                        message: "Password must be at least 8 characters long and include at least three of: uppercase, lowercase, numbers, and symbols",
                                                    },
                                                })}
                                            />
                                            <button
                                                className="btn btn-outline-primary"
                                                type="button"
                                                onClick={() => setShowPassword(!showPassword)}
                                            >
                                                {showPassword ? 'Hide' : 'Show'}
                                            </button>
                                        </div>
                                        {renderError('console_password')}

                                        {/* Password Requirements */}
                                        <div className="mt-2">
                                            <small className="text-muted">Password requirements:</small>
                                            <ul className="small text-muted mb-0">
                                                <li>Must be at least 8 characters long</li>
                                                <li>Must include at least three of the following mix of character types: uppercase letters (A-Z), lowercase letters (a-z), numbers (0-9), and symbols !@#$%^&*()_+-=[]{ }|`</li>
                                            </ul>
                                        </div>
                                    </FormGroup>

                                    <div className="form-check">
                                        <input
                                            className="form-check-input"
                                            type="checkbox"
                                            id="forcePasswordChange"
                                            checked={forcePasswordChange}
                                            onChange={(e) => setForcePasswordChange(e.target.checked)}
                                        />
                                        <label className="form-check-label" htmlFor="forcePasswordChange">
                                            <strong>Users must create a new password at next sign-in - Recommended</strong>
                                        </label>
                                    </div>
                                </>
                            )}


                        </div>
                    </CardBody>
                </Card>
                {/* <div className="mt-4"> */}
                {/* <h5 className="mb-3">Console password</h5> */}

                {/* Password Type Selection */}


            </ModalBody>
            <ModalFooter className='px-4 pb-4'>
                <>
                    <Button
                        color='danger'
                        icon='Close'
                        className='me-2'
                        onClick={() => setIsOpen(false)}
                    >
                        Close
                    </Button>
                    <div>
                        <SaveIconButton
                            waitingForAxios={waitingForAxios}
                            onClickfunc={handleSubmit(onSubmit)}
                        />
                    </div>
                </>
            </ModalFooter>
        </Modal>
    );
};

AddUser.propTypes = {
    isOpen: PropTypes.bool.isRequired,
    setIsOpen: PropTypes.func.isRequired,
    title: PropTypes.string.isRequired,
};

export default AddUser; 